# Generated by Django 4.1.5 on 2023-01-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='resultado',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
